/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalendarNavigation: typeof import('./src/components/Todo/CalendarNavigation.vue')['default']
    ConfirmDeleteButton: typeof import('./src/components/Todo/ConfirmDeleteButton.vue')['default']
    EditButton: typeof import('./src/components/Todo/EditButton.vue')['default']
    EditTodoButton: typeof import('./src/components/Todo/EditTodoButton.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    Message: typeof import('primevue/message')['default']
    NewTask: typeof import('./src/components/Todo/NewTask.vue')['default']
    OptionsMenu: typeof import('./src/components/Options/OptionsMenu.vue')['default']
    OptionsUser: typeof import('./src/components/Options/OptionsUser.vue')['default']
    RequiredStar: typeof import('./src/components/RequiredStar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareConfirmDialog: typeof import('./src/components/Todo/ShareConfirmDialog.vue')['default']
    SharedByMeIndicator: typeof import('./src/components/Todo/SharedByMeIndicator.vue')['default']
    ShareWithOthers: typeof import('./src/components/Todo/ShareWithOthers.vue')['default']
    TodoItem: typeof import('./src/components/Todo/TodoItem.vue')['default']
    UnshareButton: typeof import('./src/components/Todo/UnshareButton.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
