/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertError: typeof import('./src/components/AlertError.vue')['default']
    AuthComponent: typeof import('./src/components/AuthComponent.vue')['default']
    CalendarNavigation: typeof import('./src/components/Todo/CalendarNavigation.vue')['default']
    ConfirmDeleteButton: typeof import('./src/components/Todo/ConfirmDeleteButton.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    NewTask: typeof import('./src/components/Todo/NewTask.vue')['default']
    OptionsMenu: typeof import('./src/components/Options/OptionsMenu.vue')['default']
    OptionsUser: typeof import('./src/components/Options/OptionsUser.vue')['default']
    PageForm: typeof import('./src/components/PageForm.vue')['default']
    RequiredStar: typeof import('./src/components/RequiredStar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoItem: typeof import('./src/components/Todo/TodoItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
