services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432"
    volumes:
      - tio-db:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - ./server/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      PORT: 3000
    ports:
      - "3000"
    depends_on:
      - postgres

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      API_PROXY_PASS: http://server:3000
    ports:
      - "3001:80"
    depends_on:
      - server

volumes:
  tio-db:
